export * from "./kube-schema"

import {
  APPLY_RESOURCE,
  DELETE_RESOURCE,
  DESCRIBE_RESOURCE,
  GET_RESOURCE,
  LIST_RESOURCE,
  LOG_RESOURCE,
  PATCH_RESOURCE
} from "./kube-schema";


export const KUBE_TOOLS = [
  LIST_RESOURCE,
  GET_RESOURCE,
  APPLY_RESOURCE,
  PATCH_RESOURCE,
  DELETE_RESOURCE,
  LOG_RESOURCE,
  // DESCRIBE_RESOURCE
]